// playground/nuxt/components/Modal.vue
<script setup lang="ts">
interface ModalProps {
  isOpen: boolean
  title: string
}

defineProps<ModalProps>()

defineEmits<{
  close: []
}>()
</script>

<template>
  <div v-if="isOpen" class="modal-overlay" @click="$emit('close')">
    <div class="modal" @click.stop>
      <div class="modal-header">
        <h2 class="modal-title">{{ title }}</h2>
        <button class="modal-close" type="button" @click="$emit('close')">
          x
        </button>
      </div>
      <slot />
    </div>
  </div>
</template>

// playground/next/app/components/Modal.tsx
'use client'

import type { ReactNode } from 'react'

export interface ModalProps {
  isOpen: boolean
  title: string
  onClose: () => void
  children: ReactNode
}

export function Modal({ isOpen, title, onClose, children }: ModalProps) {
  if (!isOpen) return null

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <h2 className="modal-title">{title}</h2>
          <button
            type="button"
            className="modal-close"
            onClick={onClose}
            aria-label="Close modal"
          >
            ✕
          </button>
        </div>
        <div className="modal-body">{children}</div>
      </div>
    </div>
  )
}
