// playground/nuxt/components/TaskList.vue
<script setup lang="ts">
interface TaskListProps {
  title: string
  count?: number
}

defineProps<TaskListProps>()
</script>

<template>
  <section class="task-list">
    <div class="task-list-header">
      <h2 class="task-list-title">{{ title }}</h2>
      <span v-if="count !== undefined" class="task-list-count">{{ count }} tasks</span>
    </div>
    <slot />
  </section>
</template>

// playground/next/app/components/TaskList.tsx
'use client'

import type { ReactNode } from 'react'

export interface TaskListProps {
  title: string
  count?: number
  children: ReactNode
}

export function TaskList({ title, count, children }: TaskListProps) {
  return (
    <section className="task-list">
      <div className="task-list-header">
        <h2 className="task-list-title">{title}</h2>
        {count !== undefined && (
          <span className="task-list-count">{count} tasks</span>
        )}
      </div>
      {children}
    </section>
  )
}
