// playground/next/app/components/Button.tsx
'use client'

import type { ReactNode } from 'react'

export interface ButtonProps {
  variant?: 'primary' | 'secondary'
  size?: 'default' | 'small'
  onClick?: () => void
  children: ReactNode
}

export function Button({
  variant = 'primary',
  size = 'default',
  onClick,
  children,
}: ButtonProps) {
  const className = ['btn', `btn-${variant}`, size === 'small' && 'btn-small']
    .filter(Boolean)
    .join(' ')

  return (
    <button className={className} onClick={onClick}>
      {children}
    </button>
  )
}

// playground/nuxt/components/Button.vue
<script setup lang="ts">
import { computed } from 'vue'

interface ButtonProps {
  variant?: 'primary' | 'secondary'
  size?: 'default' | 'small'
}

const props = withDefaults(defineProps<ButtonProps>(), {
  variant: 'primary',
  size: 'default',
})

defineEmits<{
  click: []
}>()

const className = computed(() => [
  'btn',
  `btn-${props.variant}`,
  props.size === 'small' ? 'btn-small' : undefined,
])
</script>

<template>
  <button :class="className" @click="$emit('click')">
    <slot />
  </button>
</template>
