// playground/next/app/components/Header.tsx
'use client'

export interface HeaderProps {
  title: string
  userName: string
}

export function Header({ title, userName }: HeaderProps) {
  return (
    <header className="header">
      <div className="header-title">
        <div className="header-title-icon" />
        {title}
      </div>
      <div className="header-user">
        <span>{userName}</span>
        <div className="header-avatar" />
      </div>
    </header>
  )
}

// playground/vue/src/components/Header.vue
<script setup lang="ts">
interface HeaderProps {
  title: string
  userName: string
}

defineProps<HeaderProps>()
</script>

<template>
  <header class="header">
    <div class="header-title">
      <div class="header-title-icon" />
      {{ title }}
    </div>
    <div class="header-user">
      <span>{{ userName }}</span>
      <div class="header-avatar" />
    </div>
  </header>
</template>
