// playground/next/app/components/Select.tsx
'use client'

export interface SelectProps {
  id?: string
  name?: string
  label: string
  value: string
  options: Array<{ value: string; label: string }>
  required?: boolean
  onChange: (value: string) => void
}

export function Select({
  id,
  name,
  label,
  value,
  options,
  required = false,
  onChange,
}: SelectProps) {
  const selectId = id || name || label.toLowerCase().replace(/\s+/g, '-')

  return (
    <label htmlFor={selectId} className="input-field">
      <span className="input-label">{label}</span>
      <select
        id={selectId}
        name={name || selectId}
        value={value}
        required={required}
        className="select-control"
        onChange={(event) => onChange(event.target.value)}
      >
        <option value="">Select {label.toLowerCase()}...</option>
        {options.map((option) => (
          <option key={option.value} value={option.value}>
            {option.label}
          </option>
        ))}
      </select>
    </label>
  )
}

// playground/vue/src/components/Select.vue
<script setup lang="ts">
import { computed } from 'vue'

interface SelectOption {
  value: string
  label: string
}

interface SelectProps {
  id?: string
  name?: string
  label: string
  value: string
  options: SelectOption[]
  required?: boolean
}

const props = withDefaults(defineProps<SelectProps>(), {
  required: false,
})

const emit = defineEmits<{
  'update:value': [value: string]
}>()

const selectId = computed(
  () => props.id || props.name || props.label.toLowerCase().replace(/\s+/g, '-'),
)
</script>

<template>
  <label :for="selectId" class="input-field">
    <span class="input-label">{{ label }}</span>
    <select
      :id="selectId"
      :name="name || selectId"
      :value="value"
      :required="required"
      class="select-control"
      @change="emit('update:value', ($event.target as HTMLSelectElement).value)"
    >
      <option value="">Select {{ label.toLowerCase() }}...</option>
      <option v-for="option in options" :key="option.value" :value="option.value">
        {{ option.label }}
      </option>
    </select>
  </label>
</template>
