// playground/next/app/components/TaskCard.tsx
'use client'

import { Button } from './Button'
import { Badge } from './Badge'

export interface Task {
  id: string
  title: string
  status: 'pending' | 'in-progress' | 'completed'
  metadata: {
    priority: 'high' | 'medium' | 'low'
    dueDate: string
    assignee: {
      name: string
      avatar?: string
    }
  }
}

export interface TaskCardProps {
  task: Task
  onAction?: () => void
}

export function TaskCard({ task, onAction }: TaskCardProps) {
  const { title, status, metadata } = task
  const { priority, dueDate, assignee } = metadata

  return (
    <div className="task-card">
      <div className="task-card-header">
        <span className="task-card-title">{title}</span>
        <Badge status={status} />
      </div>
      <div className="task-card-meta">
        <span className="task-card-priority">
          <span className={`task-card-priority-dot ${priority}`} />
          {priority}
        </span>
        <span className="task-card-due">📅 {dueDate}</span>
        <span>👤 {assignee.name}</span>
      </div>
      {onAction && (
        <div style={{ marginTop: '0.75rem' }}>
          <Button variant="secondary" size="small" onClick={onAction}>
            View Details
          </Button>
        </div>
      )}
    </div>
  )
}

// playground/vue/src/components/TaskCard.vue
<script setup lang="ts">
import Button from './Button.vue'
import Badge from './Badge.vue'

export interface Task {
  id: string
  title: string
  status: 'pending' | 'in-progress' | 'completed'
  metadata: {
    priority: 'high' | 'medium' | 'low'
    dueDate: string
    assignee: {
      name: string
      avatar?: string
    }
  }
}

interface TaskCardProps {
  task: Task
  showAction?: boolean
}

defineProps<TaskCardProps>()

defineEmits<{
  action: []
}>()
</script>

<template>
  <div class="task-card">
    <div class="task-card-header">
      <span class="task-card-title">{{ task.title }}</span>
      <Badge :status="task.status" />
    </div>
    <div class="task-card-meta">
      <span class="task-card-priority">
        <span class="task-card-priority-dot" :class="task.metadata.priority" />
        {{ task.metadata.priority }}
      </span>
      <span class="task-card-due">📅 {{ task.metadata.dueDate }}</span>
      <span>👤 {{ task.metadata.assignee.name }}</span>
    </div>
    <div v-if="showAction" style="margin-top: 0.75rem">
      <Button variant="secondary" size="small" @click="$emit('action')">
        View Details
      </Button>
    </div>
  </div>
</template>
